travis:
  secure:
    BINSTAR_TOKEN: h1O36nvoEnZOr8h1U+imFYCyuKRcNKN6oss69colmTxPasKBJOnwZNRL41WJHhLuaXse6eaR3vDztlGVhUWZkPVVRbExESeyIY21qEzGigDSSGYRlsrv2QsvVckGSxUeLKRA8GqP89ngqRT6YhNAPKgHp0koY0EuJjUw78pATU9Pv0RMD+GP0U5hKXyBpKAC1CiEdzmcTWj7p4fLzV/mxckoqUe+tigbxzWFnHFtVzCdeZii23RgeZGiBUtjYszEKmlFaIJZxEarbiFMt9D3KKHKtjYYevDuyL37YMKNsrN5qcXImtbqlGFMdcuZDGyMDFnoO6fffvM8zkGuGEfcGrhpv2eAImVdnk/iCQqM1dyW3YE0Mzk8co6xT1S5s8pwt1QuQZJpkFTrovw4L96WbMVJpyqHgJfbWylmt5pfZGnVKMbbz5C/TploqWYCXYL1PAAOglpsYnDKFKhBd+c2lnxBacwZwa/j0Zmx1E5lMpFvYWXsOzp2H1pt0wcyTEGoON7n0CgGbZPFb86tjYofLeP0Ba3TQDRhmZrJ6OzKhBZi2RasLWUH8jwG8DWMIGQqcdqASwSEN9QeoSxvSLB5kw2DxfikytCQwWXWaITuo9aoEwAT3nhFp0DEq4XRxWfzlG1Q+dXaoeZgdfg5t9GXQD/sfcnsmphv0aoZVWn67Z4=
bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
